M48
; DRILL file {KiCad 9.0.6} date 2025-12-28T14:18:28-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-28T14:18:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X155.2Y-115.25
X162.0Y-115.25
T2
X143.75Y-95.0
M30
